server {
    listen 80;

    resolver 127.0.0.11 ipv6=off valid=10s;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $backend_url backend:5000;
        proxy_pass http://$backend_url;
    }
}