services:

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:${IMAGE_TAG}
    container_name: frontend-dev

    ports:
      - "8080:80"

    depends_on:
      - backend

    networks:
      - frontend-network-dev


  backend:
    image: ${DOCKERHUB_USERNAME}/backend:${IMAGE_TAG}
    container_name: backend-dev

    environment:
      DB_HOST: database
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: appdb

    depends_on:
      - database

    networks:
      - frontend-network-dev
      - backend-network-dev


  database:
    image: mysql:8.4
    container_name: database-dev

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword

    volumes:
      - mysql-data-dev:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - backend-network-dev


volumes:
  mysql-data-dev:


networks:

  frontend-network-dev:
    driver: bridge

  backend-network-dev:
    driver: bridge